### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by hjanuschka** [zaeleus/ffi-gphoto2#13]
hello

having issues with (broken down to suspected code)

```
device = GPhoto2::Camera.first
data = device.preview.data
```

leaks - i call the `data = device.preview.data`  in a loop - to get a updated preview - works - but seems that memory is leaking

how can i check and verify that this is called https://github.com/zaeleus/ffi-gphoto2/blob/1d0c93f8bc19e4a9f21257700953d21aa6d23e31/lib/ffi/gphoto2/camera_file.rb#L24

actual code:

```
while true
          sleep 0.5
          @mutex.synchronize do
           file = device.preview
           self.preview = file.data
          end
          if shutdown
            break
          end
      end

```

if i remove the `device.preview` - and do `self.preview="123"` the leak is gone.

regards
helmut

**Comment by hjanuschka** [comment]
ok found the solution :)


```
FFI::GPhoto2::CameraFile.release(file.ptr)
```

after the self.preview assign of data :)
going todo a PR for a release method on the CameraFile

**Comment by zaeleus** [comment]
Thanks for the report and patch! I was able to reproduce the leak.

I spent some time investigating this because it's quite irksome that the releaser isn't properly being invoked. `FFI::GPhoto2::CameraFile` is an `FFI::ManagedStruct`, meaning it wraps an autopointer that should free itself when Ruby's garbage collector runs.

Surprisingly, `ffi` throws away exceptions thrown in the defined `release` method. `gp_file_free` was actually throwing a `TypeError` because it expected a `CameraFile` and not `FFI::Pointer`, which is what the releaser passed it.

I fixed this issue in 8aa1bac, so please try `master` to test it.

**Comment by hjanuschka** [comment]
perfect,many thx man!
i can confirm that using 8aa1bac via Gemfile fixes the memory leak without calling any release function my own!



can you push a new release?

@zaeleus

**Comment by zaeleus** [comment]
Great! I tagged 0.6.1 with the fix.

**Comment by hjanuschka** [comment]
@zaeleus  thx
